
import { Inter } from 'next/font/google'
import './globals.css'
import Property1Group179 from './components/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'kilope ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body className={inter.className}>
      <Property1Group179/>
        {children}

        </body>
      
    </html>
  )
}
